In [1]:
from img2table.document import PDF

pdf = PDF("AQI_Bulletin_20241202.pdf")

In [2]:
extracted_tables = pdf.extract_tables()

print(f"Found {len(extracted_tables)} tables")

Found 14 tables

In [3]:
extracted_tables[0][0].df

,0,1,2,3,4,5
0,S.No,City,Air Quality,Index\nValue,Prominent Pollutant,No. of Stations\nParticipated/\nTotal Stations
1,1,Agartala,Moderate,170,PM2.5,1/2
2,2,Agra,Moderate,102,PM10,6/6
3,3,Ahmedabad,Moderate,131,"O3 , PM10, PM2.5",9/9
4,4,Aizawl,Good,18,PM10,1/1
5,5,Ajmer,Moderate,105,PM2.5,1/1
6,6,Akola,Satisfactory,98,PM10,1/1
7,7,Alwar,Satisfactory,78,PM10,1/1
8,8,Amaravati,Good,49,CO,1/1
9,9,Ambala,Moderate,103,PM10,1/1
10,10,Amravati,Moderate,117,"PM10, PM2.5",2/2
11,11,Amritsar,Moderate,160,PM2.5,1/1
12,12,Angul,Moderate,118,PM2.5,1/1
13,13,Ankleshwar,Moderate,176,PM2.5,1/1
14,14,Araria,Moderate,194,PM2.5,1/1
15,15,Arrah,Poor,285,PM2.5,1/1
16,16,Asansol,Poor,252,PM2.5,4/4
17,17,Aurangabad (Bihar),Moderate,170,PM2.5,1/1
18,18,Aurangabad\n(Maharashtra),Moderate,105,"PM10, PM2.5",3/3
19,19,Baddi,Poor,217,PM2.5,1/1
20,20,Badlapur,Moderate,178,PM2.5,1/1

In [34]:
df = extracted_tables[0][0].df

# Move the first column into the header
df.columns = df.loc[0]
df = df.drop(index=0)

In [6]:
from img2table.document import PDF

pdf = PDF("AQI_Bulletin_20241202.pdf")

extracted_tables = pdf.extract_tables()

for key, value in extracted_tables.items():
    print(f"{pdf.src}: Page {key} has {len(value)} tables")

AQI_Bulletin_20241202.pdf: Page 0 has 1 tables
AQI_Bulletin_20241202.pdf: Page 1 has 1 tables
AQI_Bulletin_20241202.pdf: Page 2 has 1 tables
AQI_Bulletin_20241202.pdf: Page 3 has 1 tables
AQI_Bulletin_20241202.pdf: Page 4 has 1 tables
AQI_Bulletin_20241202.pdf: Page 5 has 1 tables
AQI_Bulletin_20241202.pdf: Page 6 has 1 tables
AQI_Bulletin_20241202.pdf: Page 7 has 1 tables
AQI_Bulletin_20241202.pdf: Page 8 has 1 tables
AQI_Bulletin_20241202.pdf: Page 9 has 1 tables
AQI_Bulletin_20241202.pdf: Page 10 has 1 tables
AQI_Bulletin_20241202.pdf: Page 11 has 1 tables
AQI_Bulletin_20241202.pdf: Page 12 has 1 tables
AQI_Bulletin_20241202.pdf: Page 13 has 1 tables

In [8]:
extracted_tables[1][0].df

,0,1,2,3,4,5
0,S.No,City,Air Quality,Index\nValue,Prominent Pollutant,No. of Stations\nParticipated/\nTotal Stations
1,21,Bagalkot,Good,46,PM10,1/1
2,22,Baghpat,Moderate,132,PM10,1/2
3,23,Bahadurgarh,Poor,208,PM2.5,1/1
4,24,Balasore,Satisfactory,95,PM2.5,1/1
5,25,Baran,Moderate,148,PM2.5,1/1
6,26,Barbil,Moderate,103,PM10,1/1
7,27,Bareilly,Satisfactory,86,PM10,2/2
8,28,Baripada,Satisfactory,90,PM10,1/1
9,29,Barmer,Moderate,105,PM10,1/1
10,30,Barrackpore,Moderate,162,PM2.5,1/1
11,31,Bathinda,Satisfactory,67,PM10,1/1
12,32,Belapur,Moderate,135,PM10,1/1
13,33,Bengaluru,Satisfactory,53,"CO, PM10",10/14
14,34,Bhagalpur,Moderate,154,PM2.5,2/2
15,35,Bharatpur,Moderate,173,O3,1/1
16,36,Bhilai,Satisfactory,51,PM10,3/3
17,37,Bhilwara,Poor,203,PM2.5,1/1
18,38,Bhiwadi,Moderate,124,"PM10, PM2.5",2/2
19,39,Bhiwandi,Moderate,133,PM2.5,1/1
20,40,Bhiwani,Moderate,189,PM2.5,1/1

In [9]:
import pandas as pd

dfs = []

# For every page...
for page in extracted_tables.values():
    # For every table on that page...
    for table in page:
        # Add it to the list
        dfs.append(table.df)


# or be crazy and use a list comprehension
# dfs = [table.df for table in page for page in extracted_tables.values()]

df = pd.concat(dfs, ignore_index=True)
df.head()

,0,1,2,3,4,5
0,S.No,City,Air Quality,Index\nValue,Prominent Pollutant,No. of Stations\nParticipated/\nTotal Stations
1,1,Agartala,Moderate,170,PM2.5,1/2
2,2,Agra,Moderate,102,PM10,6/6
3,3,Ahmedabad,Moderate,131,"O3 , PM10, PM2.5",9/9
4,4,Aizawl,Good,18,PM10,1/1

In [10]:
df.columns = df.loc[0]
df = df.drop(index=0)
df.head()

,S.No,City,Air Quality,Index\nValue,Prominent Pollutant,No. of Stations\nParticipated/\nTotal Stations
1,1,Agartala,Moderate,170,PM2.5,1/2
2,2,Agra,Moderate,102,PM10,6/6
3,3,Ahmedabad,Moderate,131,"O3 , PM10, PM2.5",9/9
4,4,Aizawl,Good,18,PM10,1/1
5,5,Ajmer,Moderate,105,PM2.5,1/1

In [11]:
df.head(40)

,S.No,City,Air Quality,Index\nValue,Prominent Pollutant,No. of Stations\nParticipated/\nTotal Stations
1,1,Agartala,Moderate,170,PM2.5,1/2
2,2,Agra,Moderate,102,PM10,6/6
3,3,Ahmedabad,Moderate,131,"O3 , PM10, PM2.5",9/9
4,4,Aizawl,Good,18,PM10,1/1
5,5,Ajmer,Moderate,105,PM2.5,1/1
6,6,Akola,Satisfactory,98,PM10,1/1
7,7,Alwar,Satisfactory,78,PM10,1/1
8,8,Amaravati,Good,49,CO,1/1
9,9,Ambala,Moderate,103,PM10,1/1
10,10,Amravati,Moderate,117,"PM10, PM2.5",2/2
11,11,Amritsar,Moderate,160,PM2.5,1/1
12,12,Angul,Moderate,118,PM2.5,1/1
13,13,Ankleshwar,Moderate,176,PM2.5,1/1
14,14,Araria,Moderate,194,PM2.5,1/1
15,15,Arrah,Poor,285,PM2.5,1/1
16,16,Asansol,Poor,252,PM2.5,4/4
17,17,Aurangabad (Bihar),Moderate,170,PM2.5,1/1
18,18,Aurangabad\n(Maharashtra),Moderate,105,"PM10, PM2.5",3/3
19,19,Baddi,Poor,217,PM2.5,1/1
20,20,Badlapur,Moderate,178,PM2.5,1/1
21,S.No,City,Air Quality,Index\nValue,Prominent Pollutant,No. of Stations\nParticipated/\nTotal Stations
22,21,Bagalkot,Good,46,PM10,1/1
23,22,Baghpat,Moderate,132,PM10,1/2
24,23,Bahadurgarh,Poor,208,PM2.5,1/1
25,24,Balasore,Satisfactory,95,PM2.5,1/1
26,25,Baran,Moderate,148,PM2.5,1/1
27,26,Barbil,Moderate,103,PM10,1/1
28,27,Bareilly,Satisfactory,86,PM10,2/2
29,28,Baripada,Satisfactory,90,PM10,1/1
30,29,Barmer,Moderate,105,PM10,1/1
31,30,Barrackpore,Moderate,162,PM2.5,1/1
32,31,Bathinda,Satisfactory,67,PM10,1/1
33,32,Belapur,Moderate,135,PM10,1/1
34,33,Bengaluru,Satisfactory,53,"CO, PM10",10/14
35,34,Bhagalpur,Moderate,154,PM2.5,2/2
36,35,Bharatpur,Moderate,173,O3,1/1
37,36,Bhilai,Satisfactory,51,PM10,3/3
38,37,Bhilwara,Poor,203,PM2.5,1/1
39,38,Bhiwadi,Moderate,124,"PM10, PM2.5",2/2
40,39,Bhiwandi,Moderate,133,PM2.5,1/1

In [22]:
df_filtered = df[~df['S.No'].str.contains('S.No', case=False, na=False)]
df_filtered.head(100)

,S.No,City,Air Quality,Index\nValue,Prominent Pollutant,No. of Stations\nParticipated/\nTotal Stations
1,1,Agartala,Moderate,170,PM2.5,1/2
2,2,Agra,Moderate,102,PM10,6/6
3,3,Ahmedabad,Moderate,131,"O3 , PM10, PM2.5",9/9
4,4,Aizawl,Good,18,PM10,1/1
5,5,Ajmer,Moderate,105,PM2.5,1/1
...,...,...,...,...,...,...
100,96,Hanumangarh,Poor,205,PM2.5,1/1
101,97,Hapur,Moderate,104,PM2.5,1/1
102,98,Haveri,Good,42,SO2,1/1
103,99,Hisar,Moderate,189,PM2.5,1/1
104,100,Howrah,Moderate,174,PM2.5,4/5

In [32]:
df = df_filtered[:-7]
df.tail()

,S.No,City,Air Quality,Index\nValue,Prominent Pollutant,No. of Stations\nParticipated/\nTotal Stations
249,238,Virudhunagar,Satisfactory,53,PM10,1/1
250,239,Visakhapatnam,Good,45,PM2.5,1/1
251,240,Vrindavan,Moderate,122,PM10,1/1
253,241,Yadgir,Satisfactory,65,PM2.5,1/1
254,242,Yamuna Nagar,Moderate,157,PM2.5,1/1

In [33]:
df.to_csv('INDIA_AQI_FINAL.csv', index=False)